// GITHUB PAGES PRODUCTION KEYS

export const apiKey = 'AIzaSyDnsEfJ_v0V2KyQPz3Cryoy_n45a3UkUqc'

export const NEXT_PUBLIC_SUPABASE_URL = 'https://lvrmflqdaqviurveuulr.supabase.co'
export const NEXT_PUBLIC_SUPABASE_API_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2cm1mbHFkYXF2aXVydmV1dWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzA5NzUzMjIsImV4cCI6MjA0NjU1MTMyMn0.w3EVAMOCt5Jb96t8slj4oBccllRKnPRY0rZUJ9Yk-6w'
