import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "sonner";
// import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
      <html lang="en">
        <body>
          <Provider>
            <Toaster />
            {children}
          </Provider>
        </body>
      </html>
    // </ClerkProvider>
  );
}